<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>    <GenerateDocumentationFile>true</GenerateDocumentationFile>    <Title>Corner49 Infra</Title>
    <Authors>Frank Vanderlinden</Authors>
    <Description>An opinionated set of infrastructure libraries for .Net applications </Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Hangfire.MemoryStorage" Version="1.8.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="10.0.11" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Microsoft.Azure.SignalR.Management" Version="1.33.1" />
    <PackageReference Include="Microsoft.ApplicationInsights" Version="3.1.2" />
    <PackageReference Include="Microsoft.Azure.AppConfiguration.AspNetCore" Version="8.6.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="3.1.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.AzureAppServices" Version="10.0.11" />
    <PackageReference Include="OpenTelemetry.Api" Version="1.18.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.17.2" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
    <PackageReference Include="Auth0.AspNetCore.Authentication" Version="1.11.0" />
    <PackageReference Include="Hangfire" Version="1.8.25" />
		<PackageReference Include="Hangfire.SqlServer" Version="1.8.*" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Include="TimeZoneConverter" Version="7.2.0" />
    <PackageReference Include="SkiaSharp" Version="4.151.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Corner49.Core\Corner49.Core.csproj" />
    <ProjectReference Include="..\Corner49.CosmosDB\Corner49.CosmosDB.csproj" />
    <ProjectReference Include="..\Corner49.ServiceBus\Corner49.ServiceBus.csproj" />
    <ProjectReference Include="..\Corner49.Storage\Corner49.Storage.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="README.md">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>