<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
		<AzureCosmosDisableNewtonsoftJsonCheck>true</AzureCosmosDisableNewtonsoftJsonCheck>
		<RootNamespace>Corner49.Infra</RootNamespace>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.63.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="OpenTelemetry" Version="1.15.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Corner49.Infra.Core\Corner49.Infra.Core.csproj" />
  </ItemGroup>

</Project>
