<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
		<RootNamespace>Corner49.Infra</RootNamespace>
		<Title>Corner49 Infra Azure Storage</Title>
		<Authors>Frank Vanderlinden</Authors>
		<Description>Opinionated wrappers for Azure Blob Storage and Azure File Shares. Part of the Corner49.Infra packages</Description>
		<PackageTags>corner49;infrastructure;azure;storage;blob</PackageTags>
		<PackageProjectUrl>https://github.com/FrankVDL2471/Corner49.Infra</PackageProjectUrl>
		<RepositoryUrl>https://github.com/FrankVDL2471/Corner49.Infra</RepositoryUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Update="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Storage.Blobs" Version="12.29.2" />
		<PackageReference Include="Azure.Storage.Files.Shares" Version="12.27.1" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Corner49.Infra.Core\Corner49.Infra.Core.csproj" />
	</ItemGroup>

</Project>
