<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
		<RootNamespace>Corner49.Infra</RootNamespace>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Corner49.Infra.Core\Corner49.Infra.Core.csproj" />
  </ItemGroup>

</Project>
