name: Publish NuGet Package
 
on:
  push:
    branches:
      - main
      - 'release/*' # Trigger on any branch named 'release/*'


jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # enable GitHub OIDC token issuance for this job
    
    env:
      APP_VERSION: 10.0.${{github.run_number}}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '10.x' # Specify the .NET version you need

    - name: Print new build number
      run: echo "App version is ${{ env.APP_VERSION }}"
      # Or, if you're on Windows: echo "Build number is ${env:BUILD_NUMBER}"
 
    - name: Restore dependencies
      run: dotnet restore
 
    - name: Build the project
      run: dotnet build --configuration Release --no-restore /p:FileVersion=${{ env.APP_VERSION }} /p:AssemblyVersion=${{ env.APP_VERSION }} /p:Version=${{ env.APP_VERSION }}
 
    - name: Pack the NuGet package
      run: dotnet pack --configuration Release --no-build --output ./nupkg /p:Version=${{ env.APP_VERSION }}

    - name: NuGet login (OIDC → temp API key)
      uses: NuGet/login@v1
      id: login
      with:
        user: FrankVDL # Recommended: use a secret like ${{ secrets.NUGET_USER }} for your nuget.org username (profile name), NOT your email address
    
    - name: NuGet push Infra
      run: dotnet nuget push ./nupkg/Corner49.Infra.*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json

    - name: NuGet push Formbuilder
      run: dotnet nuget push ./nupkg/Corner49.Formbuilder.*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json

    - name: NuGet push LogViewer
      run: dotnet nuget push ./nupkg/Corner49.LogViewer.*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
