name: Publish NuGet Package
 
on:
  push:
    branches:
      - main
      - 'release/*' # Trigger on any branch named 'release/*'


jobs:
  publish:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.x' # Specify the .NET version you need

    - name: Generate build number
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}        
    - name: Print new build number
      run: echo "Build number is $BUILD_NUMBER"
      # Or, if you're on Windows: echo "Build number is ${env:BUILD_NUMBER}"
 
    - name: Restore dependencies
      run: dotnet restore
 
    - name: Build the project
      run: dotnet build --configuration Release --no-restore /p:FileVersion=${{ vars:APP_VERSION }}${{ env:BUILD_NUMBER }} /p:AssemblyVersion=${{ vars:APP_VERSION }}${{ env:BUILD_NUMBER }} /p:Version=${{ vars:APP_VERSION }}${{ env:BUILD_NUMBER }}
 
    - name: Pack the NuGet package
      run: dotnet pack --configuration Release --no-build --output ./nupkg
 
    - name: Publish NuGet package
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}